version: '3'

services:
  nginx-rtmp:
    build: .
    ports:
      - 9936:1935
      - 8081:80
      - 8443:443
    environment:
      - HTTP_PORT=80
      - RTMP_PORT=1935
    volumes:
      - ./certs:/opt/certs